### ISSUE TITLE
Description	Resource	Path	Location	Type osgi.enroute.examples.embedded.main: the ${ls} macro directory parameter does not exist: C:\tmp\osgi-enroute-examples-master\git\osgi.enroute.examples\osgi.enroute.examples.embedded\jar, for cmd: lsr, arguments; [lsr, jar]	bnd.bnd	/osgi.enroute.examples.embedded	line 1	Bndtools Problem Marker

### ISSUE THREAD

**Issue by peterkir** [osgi/osgi.enroute.examples#13]
After fresh checkout of the repo on Eclipse Mars.2 and 3.3.0.DEV-20160613-153347-g90db864

osgi.enroute.examples.embedded.main: the ${ls} macro directory parameter does not exist: C:\tmp\osgi-enroute-examples-master\git\osgi.enroute.examples\osgi.enroute.examples.embedded\jar, for cmd: lsr, arguments; [lsr, jar]  bnd.bnd /osgi.enroute.examples.embedded line 1

**Comment by pkriens** [comment]
I’ve removed the project because it actually wasn’t completely finished. And it actually got a tad to complicated.

Kind regards,

```
Peter Kriens
```
